# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Run Examples

jobs:
  build-and-run-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install dependencies
        run: |
          sudo apt-get install -y cmake libssl-dev

      - name: Cache Build Directory
        id: cache-build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-0

      - name: Init build dir
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: mkdir build

      - name: Fetch abseil
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: abseil/abseil-cpp
          ref: 215105818dfde3174fe799600bb0f3cae233d0bf
          path: build/absl-src
          fetch-depth: 0

      - name: Configure and Build Abseil
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          cd build/absl-src
          cmake . -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_CXX_STANDARD=11 -DABSL_ENABLE_INSTALL=ON
          cmake --build .

      - name: Install Abseil
        run: |
          cd build
          cmake --install absl-src --prefix ../dist

      - name: Build s2geography
        run: |
          cd build
          cmake .. -Dabsl_DIR=`pwd`/../dist/lib/x86_64-linux-gnu/cmake/absl -DBUILD_EXAMPLES=ON
          cmake --build .
          cmake --install . --prefix ../dist

      - name: Run example-simple
        run: |
          ./dist/examples/example-simple
